# Stubs for docutils.transforms.misc (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from docutils.transforms import Transform

__docformat__: str

class CallBack(Transform):
    default_priority: int = ...
    def apply(self) -> None: ...  # type: ignore

class ClassAttribute(Transform):
    default_priority: int = ...
    def apply(self) -> None: ...  # type: ignore

class Transitions(Transform):
    default_priority: int = ...
    def apply(self) -> None: ...  # type: ignore
    def visit_transition(self, node) -> None: ...
