# Stubs for docutils.transforms.writer_aux (Python 3.6)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from docutils.transforms import Transform

__docformat__: str

class Compound(Transform):
    default_priority: int = ...
    def apply(self) -> None: ...  # type: ignore

class Admonitions(Transform):
    default_priority: int = ...
    def apply(self) -> None: ...  # type: ignore
