language: python
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

stages:
  - test
  - style
  - docs

matrix:
  exclude:
    - python:
        - 3.7
        - 3.6
        - 3.5
        - 2.7
      stages:
        - style
        - docs

install:
  - python -m pip install poetry
  - python -m pip install tox

jobs:
  include:
    - stage: test
      script: tox -e py
    - stage: style
      script: tox -e style
    - stage: docs
      script: tox -e docs

notifications:
  email:
    on_success: never
    on_failure: always
