language: python
dist: xenial
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
before_install:
  - python -m pip install poetry tox tox-travis
script: tox
notifications:
  email:
    on_success: never
    on_failure: always
