language: python
dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"

install:
  - python -m pip install tox

script: tox -e py

jobs:
  include:
    - stage: style
      python: 3.7
      script: tox -e style
    - stage: docs
      python: 3.7
      script: tox -e docs

notifications:
  email:
    on_success: always
    on_failure: always
