language: python
dist: xenial
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "2.7"
stages:
  - test
matrix:
  include:
    - python: 3.7
      stages:
        - style
        - docs
jobs:
  include:
    - stage: test
      install:
        - python -m pip install poetry tox
      script: tox -e py
    - stage: style
      install:
        - python -m pip install poetry tox
      script: tox -e style
    - stage: docs
      install:
        - python -m pip install poetry tox
      script: tox -e docs
notifications:
  email:
    on_success: never
    on_failure: always
