# THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT MANUALLY.

from typing import List, Mapping, Optional, Set, Tuple, Union

import ast
import docutils.nodes


def get_fields(
        node: docutils.nodes.document,
        fields_tag: str = 'field_list'
) -> Mapping[str, str]: ...


def get_parameter_types(parameter_defs: str) -> List[str]: ...


def get_parameter_stub(
        name: str,
        type_: str,
        default: Optional[Union[ast.NameConstant, ast.Str, ast.Tuple]] = None
) -> str: ...


def get_prototype(node: ast.FunctionDef) -> Tuple[str, Set[str]]: ...


def get_stub(code: str) -> str: ...


def main() -> None: ...
